"""Add is_closed field to Form

Revision ID: 06f06a5bd862
Revises: 97091fb594ac
Create Date: 2025-05-01 17:29:03.952514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06f06a5bd862'
down_revision = '97091fb594ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_closed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('is_closed')

    # ### end Alembic commands ###
