"""Add company_id to Response table

Revision ID: 79db543bc984
Revises: e389c0714f86
Create Date: 2025-04-11 10:59:04.397439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79db543bc984'
down_revision = 'e389c0714f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_response_company', 'company', ['company_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_constraint('fk_response_company', type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###
