"""Add quiz fields to Response model

Revision ID: 8db1ed70dba6
Revises: cc2917320fbd
Create Date: 2025-05-05 11:48:32.579720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db1ed70dba6'
down_revision = 'cc2917320fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quiz', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('passing_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('show_score', sa.Boolean(), nullable=True))

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_quiz_question', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('correct_answer', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('points', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('feedback', sa.Text(), nullable=True))

    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('max_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('passed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('passed')
        batch_op.drop_column('max_score')
        batch_op.drop_column('score')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_column('feedback')
        batch_op.drop_column('points')
        batch_op.drop_column('correct_answer')
        batch_op.drop_column('is_quiz_question')

    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('show_score')
        batch_op.drop_column('passing_score')
        batch_op.drop_column('is_quiz')

    # ### end Alembic commands ###
