"""add utm columns to response table

Revision ID: dc0986e2e96f
Revises: 79db543bc984
Create Date: 2025-04-29 13:07:46.865594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc0986e2e96f'
down_revision = '79db543bc984'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('utm_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('utm_medium', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('utm_campaign', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('utm_content', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('utm_term', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('device_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('device_type')
        batch_op.drop_column('utm_term')
        batch_op.drop_column('utm_content')
        batch_op.drop_column('utm_campaign')
        batch_op.drop_column('utm_medium')
        batch_op.drop_column('utm_source')

    # ### end Alembic commands ###
