"""Add requires_consent to Form

Revision ID: e997885cca3c
Revises: 06f06a5bd862
Create Date: 2025-05-02 13:23:50.851924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e997885cca3c'
down_revision = '06f06a5bd862'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_consent', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('form', schema=None) as batch_op:
        batch_op.drop_column('requires_consent')

    # ### end Alembic commands ###
